config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  root to: "movies#index"
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
  #post "likes/:movie_id/create" => "likes#create"
  #post "likes/:movie_id/destroy" => "likes#destroy"
  resources :movies do
    resources :likes, only: [:create, :index, :show, :destroy]
  end  
  
  resources :rooms do
    resources :comments 
  
  end
  
  resources :users do
    member do
      get :likes
    end
  end  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
  validates :content,  presence: true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room

  def create
    @comments = @room.comments.order(created_at: :desc)
    @comment = @room.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save(created_at: :desc)
      render :index
    else
      render :index
    end
  end
  
  def destroy
    @comment = Comment.find(params[:id])
    @comments = @room.comments.order(created_at: :desc)
    @comment.destroy
      render :index

  end


  private
  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, room_id: params[:room_id])
  end
  
  def set_room
    @room = Room.find(params[:room_id])
  end  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with model: [@room, @comment], url: room_comments_path(@room) do |f|%>
    <div class="comment__field">
      <%= f.text_area :content, placeholder:"コメントを入力" ,class:"new_content"%>
      <%= f.submit 'post ▶︎' ,class:"comment__submit", id: "submit" %>
      
    </div>
<% end %>

app/views/comments/_index.html.erb
<% @comments.each do |comment| %>
      <div class="content">
        <div class="comennt-date">
          投稿日時：<%= comment.created_at %>
        
          
        </div>
        <div class="comment-content">
          <%= comment.content %>
          <%= link_to "#{comment.user.nickname}","/users/#{comment.user.id}", class: :comment_user %>
        </div>
      </div>  
        <% if comment.user == current_user %>
          <p><%= link_to 'コメントを削除する', room_comment_path(comment.room_id, comment.id), class: "delete_title",method: :delete, remote: true %></p>
        <% end %>
      
<% end %>

app/views/comments/index.js.erb
$(".comment_area").html("<%= j(render 'index', { comments: @comment.room.comments }) %>")
$(".new_content").val('')