config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  root to: "movies#index"
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
  #post "likes/:movie_id/create" => "likes#create"
  #post "likes/:movie_id/destroy" => "likes#destroy"
  resources :movies do
    resources :likes, only: [:create, :index, :show, :destroy]
  end  
  
  resources :rooms do
    resources :comments 
  
  end
  
  resources :users do
    member do
      get :likes
    end
  end  
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_one_attached :image
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre
  
  belongs_to :public_year
  
  validates :title ,presence: true
  validates :image, presence: true
  validates :director ,presence: true
  validates :starring, presence: true
  validates :genre_id, presence: true
  validates :public_year_id, presence: true
  validates :genre_id, numericality:{ other_than: 1, message: "can't be blank"}
  validates :public_year_id, numericality:{ other_than: 1, message: "can't be blank"}
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :move_to_index, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  
  def index
    @rooms = Room.all.order(public_year_id: "ASC")
  end
  
  def new
    @room = Room.new
  end
  
  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to room_path(@room.id)
    else  
      render :new

    end
  end  

  def show 
    @comment = Comment.new
    @comments = @room.comments.order(created_at: :desc)
  end
  
  def edit
  end
  
  def update
    
    if @room.update(room_params)
      redirect_to room_path(@room.id)
    else 
      render :edit
    end
  end  
  
  def destroy
    @room.destroy
    redirect_to root_path
  end  
  
  
  private

  def room_params
    params.require(:room).permit(:image, :title, :director, :starring, :genre_id, :public_year_id)
  end

  def move_to_index
    unless user_signed_in? && current_user.admin
      redirect_to action: :index
    end
  end

  def set_room
    @room = Room.find(params[:id])
  end  
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_room.html.erb
<div class="card">
  <%= link_to image_tag(room.image.variant(resize: '500x300'), class: :card__img ), room_path(room.id)%>
  <div class="card__body">
    <%= link_to "#{room.title}", root_path, class: :card__title%>
    <p class="card__summary">
      <%= "#{room.genre.name}" %>
    </p>
    <p class="card__summary">
      <%= "#{room.public_year.name}公開作品" %>
    </p>
    <p class="card__summary">
      <%= "#{room.director} / 監督" %>
    </p>
    <p class="card__summary">
      <%= "#{room.starring} / 主演" %>
    </p>
    
  </div>
</div>

app/views/rooms/edit.html.erb
<div class="rooms-contents">
  <header class="rooms-header">
    

  </header>
  <div class="rooms-main">
    <h2 class="roooms-title">映画の情報を入力</h2>
    <%= form_with model:@room, url: "/rooms/#{@room.id}", local: true do |f| %>

    
    <% render 'shared/error_messages', model: f.object %>
    

  
    <div class="img-upload">
      <div class="weight-bold-text">
        movie画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"room-image" %>
      </div>
    </div>
   
   
    <div class="new-rooms">
      <div class="weight-bold-text">
        映画のタイトル
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"rooms-text", id:"room-name", placeholder:"映画のタイトル" %>
    </div>
    

    
    <div class="rooms-detail">
      <div class="weight-bold-text">映画の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          監督
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :director, class:"rooms-text", id:"room-director" %>
        <div class="weight-bold-text">
          主演
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :starring, class:"rooms-text", id:"room-starring" %>
      </div>
    
    
      <div class="form">
        <div class="weight-bold-text">
          映画のジャンル
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"-genre"}) %>
        <div class="weight-bold-text">
          映画の公開年
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:public_year_id, PublicYear.all, :id, :name, {}, {class:"select-box", id:"room-public-year"}) %>
        
      </div>
      
      
      
    </div>    
    <%# 下部ボタン %>
    <div class="rooms-up-btn-contents">
      <%= f.submit "edit room" ,class:"rooms-up-btn" %>
      <%=link_to 'back', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="rooms-footer">
    
    <p class="inc">
     <%= link_to image_tag("39be9118e271f0256ea4a09c10ba3989.png", class: "root_logo"), root_path %>
    </p>
  </footer>
  
</div>

app/views/rooms/index.html.erb
<!DOCTYPE html>
<div class="main">
  <div class='room-image-area'>
    <div class="rooms-heading">
      <link href="https://fonts.googleapis.com/css?family=Corben:700" rel="stylesheet">
      <%= "movie chat" %>
    </div>  
    <p class='rooms-service-explain'>
      Let's click on the movie!!
    </p>  
    <p class='rooms-service-explain'>
      
    </p>
  </div>
</div>
  
  
<div class="r-main">
<div class="denger">※チャット内容はネタバレを含む場合がございます。</div>
  <div class="index__inner">
    <div class="card__wrapper">
      <%= render partial: "rooms/room", collection: @rooms %>
    </div>
  </div>
    
    
</div>

app/views/rooms/new.html.erb
<div class="rooms-contents">
  <header class="rooms-header">
    
  </header>
  <div class="rooms-main">
    <h2 class="roooms-title">映画の情報を入力</h2>
    <%= form_with model:@room, url: rooms_path,local: true do |f| %>

  
    <div class="img-upload">
      <div class="weight-bold-text">
        movie画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"room-image" %>
      </div>
    </div>
   
   
    <div class="new-rooms">
      <div class="weight-bold-text">
        映画のタイトル
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"rooms-text", id:"room-name", placeholder:"映画のタイトル" %>
    </div>
    

    
    <div class="rooms-detail">
      <div class="weight-bold-text">映画の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          監督
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :director, class:"rooms-text", id:"room-director" %>
        <div class="weight-bold-text">
          主演
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :starring, class:"rooms-text", id:"room-starring" %>
      </div>
    
    
      <div class="form">
        <div class="weight-bold-text">
          映画のジャンル
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"room-genre"}) %>
        <div class="weight-bold-text">
          映画の公開年
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:public_year_id, PublicYear.all, :id, :name, {}, {class:"select-box", id:"room-public-year"}) %>
        
      </div>
      <%# 感想 %>
      
      
    </div>    
    <%# 下部ボタン %>
    <div class="rooms-up-btn-contents">
      <%= f.submit "up room" ,class:"rooms-up-btn" %>
      <%=link_to 'back', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="rooms-footer">
    
    <p class="inc">
     <%= link_to image_tag("39be9118e271f0256ea4a09c10ba3989.png", class: "root_logo"), root_path %>
    </p>
  </footer>
  
</div>

app/views/rooms/show.html.erb
<div class="chat__main">

  <div class="room__left__wrapper"> 

      <div class="room__image__cover">
        <%= image_tag @room.image, class: "room__image" %>
       
        <div class="room__heading">
          <%= "#{@room.title}"%>
        </div>
          <div class="room__list">
            
            <p class="room__list__name"><%= "#{@room.director} / 監督" %></p>
            <p class="room__list__name"><%= "#{@room.starring} / 主演" %></p>
            <p class="room__list__name"><%= "#{@room.genre.name}  " %></p>
            <p class="room__list__name"><%= "#{@room.public_year.name} 公開作品 " %></p>
          </div>
      <% if user_signed_in? && current_user.admin? %>
        <div class="movie__manage">
        
          <div class="edit__movie__btn">
          <i class="fas fa-bowling-ball fa-2x"></i><%= link_to '編集する', edit_room_path(@room.id), method: :get ,class: "edit-text"%>
          </div>
          <div class="delete__movie__btn">
          <i class="fas fa-bowling-ball fa-2x"></i><%= link_to '削除する', room_path(@room.id), method: :delete,data: { confirm: 'このroomを削除しますか？' },class: "edit-text"%>
          </div>
        </div>
      <% end %>
    
      
      </div>
  </div> 

  <div class="chat__area">
    <div class="room__heading__name">Movie chat</div>
    
    <div class="form_area">
    <% if user_signed_in? %>
    <%= render partial: "comments/form", locals: { comment: @comment ,room: @room } %>
    <% end %>
    </div>
    <div class="comment_area">
    <%if @comments.blank? %>
      <div class="comment_area" >
      <h3>コメントはありません</h3>
      </div>
    <% else %>
    <%= render partial: "comments/index", locals: { comments: @comments } %>
    <% end %>
    </div>
  
   
      
    
  </div>
</div>