config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  root to: "movies#index"
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
  #post "likes/:movie_id/create" => "likes#create"
  #post "likes/:movie_id/destroy" => "likes#destroy"
  resources :movies do
    resources :likes, only: [:create, :index, :show, :destroy]
  end  
  
  resources :rooms do
    resources :comments 
  
  end
  
  resources :users do
    member do
      get :likes
    end
  end  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" defer></script>
    <title>My movie collection</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
    <link href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      
      
      <div class="heading">
        
        <link href="https://fonts.googleapis.com/css?family=Corben:700" rel="stylesheet">
        
        <div class="title">my movies collection </div>
        
        
        
      </div>  
        
        <div class="login-area">
        
        
       
          <% if user_signed_in? %>
            <div class="hello">Hello,<%="#{current_user.nickname}"%></div>
            <div class="nav__btn">
              <i class="fas fa-compact-disc fa-2x"></i>   <%= link_to "Up Movie", new_movie_path %>
            </div>
          <%end%>  
        </div>
        
        <div class="navbar">
          <ul class="nav-lists">
            
            
    
            <% if user_signed_in? %>
            <li class="background-w" id="lists">select ▼
            </li>
            <%else%>
            <li class="background-w" id="lists">please login
            </li>
            <%end%>
          </ul>
        </div> 
        
        <div class="navbar">  
          <ul class="show-lists hidden" id="pull-down">
            <% if user_signed_in? %>  
              <% if current_user.admin?  %>
              <li class="pull-down-list">
              <%=link_to "make room", new_room_path ,class: :make__room %></li>
              <% end %>  
              <li class="pull-down-list">
              <%= link_to "my collection ページ","/users/#{current_user.id}",class: "pull-down-text"%></li>
              <li class="pull-down-list">
              <%= link_to "watchリスト ページ","/users/#{current_user.id}/likes",class: "pull-down-text"%></li>
            <%end%>  
              <li class="pull-down-list">
              <%= link_to "movie chat ページ" ,rooms_path,class: "pull-down-text"%></li>
              <li class="pull-down-list">
              <%= link_to "ホーム画面へ戻る" ,root_path,class: "pull-down-text"%></li>
          
          
            <% unless user_signed_in? %>
              <li class="pull-down-list">
              <%= link_to "新規登録", new_user_registration_path, class: "pull-down-text" %></li>
              <li class="pull-down-list">
              <%= link_to "ログイン", user_session_path,class: "pull-down-text"%></li>
            <% else %>
              <li class="pull-down-list">
              <%= link_to "アカウント",edit_user_path(current_user),class: "pull-down-text"%></li>
              <li class="pull-down-list">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete,class: "pull-down-logout" %></li>
            <%end%>
              
          </ul>
        </div>  
          
         
        
        </div>
        
    </header>
    
    <%= yield %>
    
    <footer class="footer">
      <p class="copyright">Copyright © My movies collection  All rights reserved.</p>
    </footer>
  </body>
</html>